name: Update ksu
on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - name: checkout kernel
        uses: actions/checkout@v3
        with:
          repository: Grill-Laux/kernel_oneplus_sdm845
          ref: fourteen
          
      - name: Check kernel source
        run: |
          echo "local folder"
          ls
          cd ..
          echo "go up folder"
          ls
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Update KernelSU
        run: |
          git submodule update --init --recursive --remote
          echo "### start check ksu"
          ls KernelSU 
          echo "### start check ksu"
          echo "### start check diff"
          git diff
          echo "### end check diff"
          git config --global user.email "moegluwu0@gmail.com"
          git config --global user.name "Grill-Laux"
          git commit -asm "KernelSU: ${{ env.BUILD_TIME }}"
          git push
